### PR TITLE
fix(chore): Remove all current vulnerability of loopback4-s3

### LINKED ISSUE #107: Package Update - loopback4-s3
**Describe the bug**
remove all current vulnerability of loopback4-s3

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Tyagi-Sunny**
## Description
remove all current vulnerability of loopback4-s3

Fixes #107 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: dist/types.d.ts [hunk 1]
```diff
@@ -11,5 +12,5 @@ export interface AwsS3Config {
     region?: string;
 }
 export declare class S3WithSigner extends S3 {
-    getSignedUrl(command: PutObjectCommand, options: RequestPresigningArguments): Promise<string>;
+    getSignedUrl<InputType extends ServiceInputTypes, OutputType extends MetadataBearer = MetadataBearer>(command: Command<InputType, OutputType, any, ServiceInputTypes, MetadataBearer>, options?: RequestPresigningArguments): Promise<string>;
```
Comment (yeshamavani) [inline dist/types.d.ts:15]: why dist files?

**Review by yeshamavani — CHANGES_REQUESTED** [review]

**Review by yeshamavani — APPROVED** [review]
